spring:
  application:
    name: project

  customer-datasource:
    url: jdbc:postgresql://localhost:30001/customerdb
    username: postgres
    password: postgres

  customer-flyway:
    locations: classpath:db/migration/customer
    baseline-on-migrate: true

  stations-datasource:
    url: jdbc:postgresql://localhost:30002/stationsdb
    username: postgres
    password: postgres

  stations-flyway:
    locations: classpath:db/migration/stations
    baseline-on-migrate: true

  station1-datasource:
      url: jdbc:postgresql://localhost:30011/station1db
      username: postgres
      password: postgres

  station1-flyway:
    locations: classpath:db/migration/station1
    baseline-on-migrate: true

  station2-datasource:
    url: jdbc:postgresql://localhost:30012/station2db
    username: postgres
    password: postgres

  station2-flyway:
    locations: classpath:db/migration/station2
    baseline-on-migrate: true

  station3-datasource:
    url: jdbc:postgresql://localhost:30013/station3db
    username: postgres
    password: postgres

  station3-flyway:
    locations: classpath:db/migration/station3
    baseline-on-migrate: true