version : '3.8'

services:
  customer-db:
    build:
      context: ./src/main/resources/db/migration/
      dockerfile: Dockerfile
    ports:
      - '30001:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  station-db:
    build:
      context: ./src/main/resources/db/migration/
      dockerfile: Dockerfile
    ports:
      - '30002:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  station-1-db:
    build:
      context: ./src/main/resources/db/migration/
      dockerfile: Dockerfile
    ports:
      - '30011:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  station-2-db:
    build:
      context: ./src/main/resources/db/migration/
      dockerfile: Dockerfile
    ports:
      - '30012:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  station-3-db:
    build:
      context: ./src/main/resources/db/migration/
      dockerfile: Dockerfile
    ports:
      - '30013:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  queue:
    image: rabbitmq:management-alpine
    hostname: 'rabbitmq'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=guest'
      - 'RABBITMQ_DEFAULT_USER=guest'
    ports:
      # AMQP protocol port
      - '30003:5672'
      - # RabbitMQ Management console
      - '30083:15672'
