FROM postgres:alpine

COPY customer.sql /docker-entrypoint-initdb.d/
COPY stations.sql /docker-entrypoint-initdb.d/
COPY station1.sql /docker-entrypoint-initdb.d/
COPY station2.sql /docker-entrypoint-initdb.d/
COPY station3.sql /docker-entrypoint-initdb.d/